### PR TITLE
Constants Page

### PR DESCRIPTION
**Pull request by EmilSoleymani**
Added `Constants` page in menu.

### CODE REVIEW

**Comment by smiths** [comment]
@EmilSoleymani, I'm still getting the error about the dir.dat file not existing.  Can you write code to create the file if it doesn't exist?  It could initially have the current folder as its contents.

**Comment by EmilSoleymani** [comment]
Commit eaaf3f5f0ae72bb22b67ee8d892bb65f90851dfa already deals with case when file doesn't exist and creates an empty file in this case. I think the issue has to do with the directory not existing in the current version control since it was left empty and ignored. 

In commit 17418022f1a027a4b9bb25cc655b6f24d1268912 which is on `update-meeting` branch I force this directory to exist in version control by adding a simple `README.md` file. It was also a good opportunity to document what those files are used for incase any future developers or users would like to know.

I will be submitting a PR for the `update-meeting` branch soon.

**Comment by smiths** [comment]
I'm glad to see that the constants are updated if the units are changed.  However, if I change the unit system from Imperial to Metric, the minimum layer size changes to NaN (Not A Number).

I also have some other feedback:

- I can edit the minimum layer size (in both imperial and metric), but I cannot edit the unit weight of water
- We should put some bounds on the minimum layer size.  I'm glad to see that negative numbers and zero are not allowed.  We should also have a maximum for the minimum layer size.  The maximum could be large, maybe something like 10ft, 20ft?

**Comment by EmilSoleymani** [comment]
I didn't allow users to alter the unit weight of water as I thought it didn't make sense to change a constant related to physical properties, but I wanted the user to be able to see what value was being used. I could easily add that functionality now.

I will also add the max on the MIN_LAYER_SIZE (10ft as suggested) and investigate the `NaN` issue.

**Comment by EmilSoleymani** [comment]
I am having a hard time reproducing the `NaN` bug.

I have tried updating values and changing unit systems in many combinations but for me it always seems to display the correct value. Even when I go to EnterDataStage3 and make a layer too small to get a warning popup it displays the correct value of MIN_LAYER_SIZE.

**Comment by smiths** [comment]
@EmilSoleymani, I cannot reproduce the NaN error either.  Maybe I wasn't working with the most up-to-date version when I tested last time?  Regardless, it works now, so there is nothing to do on this point.

With respect to changing the unit weight of water, you can enable this.  I agree that it won't come up often, but there are a few cases where this could be relevant:

- somebody wishes to have higher precision than what the program currently offers.  More precision is probably not justified, as Dr. Stolle has explained to us, but if the user wants it, we can provide it.
- Since the unit weight of water is based on the acceleration due to gravity, the number is different at different elevations.  I doubt it is different enough to be meaningful, but that decision is up to the user
- Although I don't know how likely it is to occur, I can imagine situations where the soil is saturated with a fluid other than water.  Maybe there has been an oil spill?  Or possibly more likely, what if the property is on the coast of the ocean and it is sea water (salt water), not fresh water?

There is also the UI aspect of displaying minimum layer and unit weight the same way, but they have a difference in functionality.  It is confusing for the user to see two edit boxes, one of which they can edit and one that they cannot edit.  If I remember the terminology correctly, an edit box is an [affordance](https://uxplanet.org/ux-design-glossary-how-to-use-affordances-in-user-interfaces-393c8e9686e4?gi=63b12dc907da#:~:text=Affordance%20is%20a%20property%20or,it%20to%20open%20the%20door.)  By looking at it the user thinks they can edit it, based on other applications.  Again, it is jarring if they can't.  If you really don't want the user to edit the field, it shouldn't be in an edit box.  :smile:

If you get a chance @EmilSoleymani, can you add a commit to this branch to resolve the merge conflict mentioned above?

**Comment by EmilSoleymani** [comment]
Conflicts resolved, and user may now edit unit weight of water

**Review by smiths — APPROVED** [review]
Great!  Thank you @EmilSoleymani

**Pull request merged**
