### PR TITLE
Output file value rounding. About Page.

### PR DESCRIPTION
**Pull request by EmilSoleymani**
# Output File

Values in output file tables are now rounded to a fixed number of decimal places.

# About Page

Added about page in settings and updated icon for "About" option in settings menu

### CODE REVIEW

**Review by smiths — COMMENTED** [review]
Why are you rounding?  I don't normally like to round the output in the "raw" form because once the extra precision is lost, it is lost forever.  Is this just for display, or is the output "losing" significant figures?

**Comment by EmilSoleymani** [comment]
The rounding is just for displaying purposes. We previously had long decimal values in output files:

image

 > Example old output

The actual `Float64` values are not changed, they are just used to construct a string rounded to a fixed number of decimal places. I wrote a `toFixed()` function in `CalculationBehaviour.jl` which is based off of Javascript's function of the same name (I actually use the Javascript `toFixed()` many times in the QML code). The actual values remain very precise (as seen in the example output from a previous version).

**Comment by smiths** [comment]
If the user takes the output files and uses these values, then the output is changed.  If a user takes the output file values and plots them, they have lost information.

Is your goal to make the output line up nicer?

Can you show me what your new file looks like?  If the goal is to get the decimal point to line up, then we can use scientific notation.

**Comment by EmilSoleymani** [comment]
Here is a sample of the new output:

image

Dr. Stolle had also previously mentioned during a meeting that the output file values have way too many decimals.

**Comment by smiths** [comment]
What happens if delta heave is `0.00015`?  What happens if delta heave is `0.000015`?  In the first case changing `0.00015` to `0.0002` is a relative change of 33%.  In the second case changing `0.000015` to `0` is a relative error of 100%.  Maybe I'm misinterpreting your rounding rules.

In the first case I would rather show `1.5e-4` and in the second case `1.5e-5`.  

I agree with @dstolle about the precision.  We don't need to show unnecessary precision.  My concern is the accuracy.

**Comment by EmilSoleymani** [comment]
I have updated the function to return scientific notation for values that would have lost all their data. Examples from the docstring:

```
julia> toFixed(54.5, 4)
"54.5000"
```

```
julia> toFixed(54.51999, 2)
"54.52"
```

```
julia> toFixed(0.0000054, 3)
"5.400e-6"
```

```
julia> toFixed(0.00024234, 3)
"2.423e-4"
```

**Review by smiths — APPROVED** [review]
Looks good @EmilSoleymani.

**Comment by dstolle** [comment]
Good point.

Von: Spencer Smith ***@***.***>
Gesendet: Montag, 15. August 2022 16:40
An: smiths/vdisp ***@***.***>
Cc: Stolle, Dieter ***@***.***>; Mention ***@***.***>
Betreff: Re: [smiths/vdisp] Output file value rounding. About Page. (PR #121)


What happens if delta heave is 0.00015? What happens if delta heave is 0.000015? In the first case changing 0.00015 to 0.0002 is a relative change of 33%. In the second case changing 0.000015 to 0 is a relative error of 100%. Maybe I'm misinterpreting your rounding rules.

In the first case I would rather show 1.5e-4 and in the second case 1.5e-5.

I agree with @dstolle<https://github.com/dstolle> about the precision. We don't need to show unnecessary precision. My concern is the accuracy.

**Pull request merged**
