### PR TITLE
FORTRAN code update

### PR DESCRIPTION
**Pull request by EmilSoleymani**
Updated legacy Fortran code in `fortran_src` directory to compile with no warnings. Kept file `VDOU_old.DAT` to compare with `VDOU.DAT` to ensure code still works.

### CODE REVIEW

**Review by smiths — CHANGES_REQUESTED** [review]
Great work @EmilSoleymani.  Nice to get your first pull request in the first day on the job!  :smile:  I have one request and one comment.

Request - please remove the file vdisp from version control.  We don't want to keep generated files (like executables) under version control.  While you are at it, you can remove VDOU_old.DAT as well.  That file was useful to close the issue, but now it doesn't have any meaning for us.

Comment - I haven't looked at FORTRAN code in more than a few years.  I forgot the ugly `GOTO`s.  We will already be improving the code just by using proper loops!

**Comment by EmilSoleymani** [comment]
Files removed

**Review by smiths — APPROVED** [review]
Great!  Thank  you for the quick work @EmilSoleymani.

**Comment by smiths** [comment]
Nice!  @EmilSoleymani, I removed the `fortranupdate` branch.  I don't think you will be using it anymore.  I'll be honest that I have a bad habit of not deleting branches and then in the future, nobody can remember if they are useful changes or not.  We should try our best to delete branches when they have outlived their usefulness.  If a branch does live a long time, we should be sure to document its purpose.

**Pull request merged**
